"""add menu tables

Revision ID: 0def3ea21839
Revises: 0b79583876df
Create Date: 2025-05-10 19:12:59.679005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0def3ea21839'
down_revision: Union[str, None] = '0b79583876df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menu_categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_categories', type_='unique')
    # ### end Alembic commands ###
